name: Learn basics of GitHub actions

on:
  push:
    branches:
    - main

jobs:
  chaloworld:
    runs-on: ubuntu-latest
    container: 
      image: alpine:latest

    steps:
     - name: print chalo
       run: cat /etc/os-release
